import { strToU8, zipSync } from 'fflate';

import { parseZipEnd, parseZipEntry } from '../zipDirectory';

function archive() {
  return zipSync({ 'manifest.json': strToU8('{}'), 'database/cherry.db': strToU8('fixture') });
}

test('reads the central directory generated by the ZIP writer', () => {
  const zip = archive();
  const directory = parseZipEnd(zip, zip.length);
  expect(directory.count).toBe(2);
  const header = zip.subarray(directory.start, directory.start + 46);
  const length = new DataView(header.buffer, header.byteOffset).getUint16(28, true);
  expect(
    parseZipEntry(header, zip.subarray(directory.start + 46, directory.start + 46 + length)),
  ).toMatchObject({ name: 'manifest.json', size: 2 });
});

test('rejects a truncated ZIP even when all individual file payloads are present', () => {
  const zip = archive();
  const directory = parseZipEnd(zip, zip.length);
  for (const length of [directory.start, zip.length - 1, zip.length - 10]) {
    expect(() => parseZipEnd(zip.subarray(0, length), length)).toThrow();
  }
});

test('rejects appended payloads, multidisk archives and central directory offset corruption', () => {
  const zip = archive();
  const appended = new Uint8Array(zip.length + 1);
  appended.set(zip);
  expect(() => parseZipEnd(appended, appended.length)).toThrow();
  for (const relativeOffset of [4, 16]) {
    const changed = zip.slice();
    changed[changed.length - 22 + relativeOffset] = 1;
    expect(() => parseZipEnd(changed, changed.length)).toThrow();
  }
});

test('rejects encrypted and symlink entries before they can be extracted', () => {
  const zip = archive();
  const directory = parseZipEnd(zip, zip.length);
  const original = zip.slice(directory.start, directory.start + 46);
  const name = strToU8('manifest.json');
  const encrypted = original.slice();
  encrypted[8] |= 1;
  expect(() => parseZipEntry(encrypted, name)).toThrow();
  const symlink = original.slice();
  new DataView(symlink.buffer).setUint32(38, 0xa0000000, true);
  expect(() => parseZipEntry(symlink, name)).toThrow();
});
